# Port ??
server:
  port: 9090

spring:
  # JPA ??
  jpa:
    hibernate:
      ddl-auto: validate
  # H2 Database ??
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  # schema.sql, data.sql ????? ????? ??
  sql:
    init:
      mode: always